spring.application.name=back-end
myapp.name=smart-clinic
# ---------------------------------------------------------------------------------------------------
# SQL Database Configuration
# ---------------------------------------------------------------------------------------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/my_database?currentSchema=clinic
#spring.datasource.url=jdbc:mysql://<mysql_host>/cms?usessl=false
spring.datasource.username=postgres
spring.datasource.password=postgres123

# ---------------------------------------------------------------------------------------------------
# Document Database (NoSql) Mongo DB
# ---------------------------------------------------------------------------------------------------
spring.data.mongodb.uri=mongodb://smartc:smartc123@localhost:27017/prescriptions?authSource=admin
#spring.data.mongodb.uri=mongodb://root:<mongodb_password>@<mongodb_host>:27017/prescriptions?authSource=admin"

# ---------------------------------------------------------------------------------------------------
# JPA/Hibernate Configuration
# ---------------------------------------------------------------------------------------------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=smart_clinic
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ---------------------------------------------------------------------------------------------------
# Health end-point
# ---------------------------------------------------------------------------------------------------
management.endpoint.health.show-details=always
management.health.db.enabled=true

# ---------------------------------------------------------------------------------------------------
# Other Configurations
# ---------------------------------------------------------------------------------------------------

api.path=/
jwt.secret=$!@#$^%$$$%####$DDCPN0234FCFDPD8670M

spring.web.resources.static-locations=classpath:/static/

# -------------------------
# Thymeleaf Configuration
# -------------------------
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false    
spring.thymeleaf.encoding=UTF-8

# ---------------------------------------------------------------------------------------------------
# logging
# ---------------------------------------------------------------------------------------------------

#logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
#logging.level.org.springframework.data.mongodb=DEBUG
#logging.level.org.mongodb.driver=DEBUG

logging.level.root=INFO
#logging.level.org.springframework.boot.context.config=DEBUG
## Application logs
#logging.level.com.project.code=DEBUG
## Spring framework
logging.level.org.springframework=INFO
## Hibernate SQL
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.SQL=OFF
#logging.level.org.hibernate.type.descriptor.sql=OFF
## Hibernate bind parameters
#logging.level.org.hibernate.orm.jdbc.bind=TRACE
#logging.level.org.hibernate.orm.jdbc.bind=OFF

# ---------------------------------------------------------------------------------------------------
# Initialize schema and data
# ---------------------------------------------------------------------------------------------------
#        --- use only to initialize data --- spring.datasource.schema=classpath:schema.sql
#        --- use only to initialize data --- spring.datasource.data=classpath:data.sql
#        --- use only to initialize data --- spring.sql.init.mode=always
#        --- use only to initialize data --- spring.jpa.defer-datasource-initialization=true

spring.datasource.schema=classpath:schema.sql
spring.datasource.data=classpath:data.sql
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
