-- ------------------------------------------
-- DROP TABLES
-- ------------------------------------------
DROP TABLE IF EXISTS smart_clinic.doctor_available_times;
DROP TABLE IF EXISTS smart_clinic.appointment;
DROP TABLE IF EXISTS smart_clinic.patient;
DROP TABLE IF EXISTS smart_clinic.doctor;
DROP TABLE IF EXISTS smart_clinic.admin;

-- ------------------------------------------
-- CREATE TABLES
-- ------------------------------------------

-- ------------------------------------------
-- Table: smart_clinic.admin
-- ------------------------------------------
CREATE TABLE IF NOT EXISTS smart_clinic.admin
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    username character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT admin_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS smart_clinic.admin
    OWNER to postgres;

-- ------------------------------------------
-- Table: smart_clinic.doctor
-- ------------------------------------------
CREATE TABLE IF NOT EXISTS smart_clinic.doctor
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    specialty character varying(50) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT doctor_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS smart_clinic.doctor
    OWNER to postgres;

-- ------------------------------------------
-- Table: smart_clinic.patient
-- ------------------------------------------
CREATE TABLE IF NOT EXISTS smart_clinic.patient
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(255) COLLATE pg_catalog."default" NOT NULL,
    address character varying(255) COLLATE pg_catalog."default" NOT NULL,
    date_of_birth date,
    emergency_contact character varying(255) COLLATE pg_catalog."default",
    insurance_provider character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT patient_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS smart_clinic.patient
    OWNER to postgres;

-- ------------------------------------------
-- Table: smart_clinic.appointment
-- ------------------------------------------
CREATE TABLE IF NOT EXISTS smart_clinic.appointment
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    doctor_id bigint NOT NULL,
    patient_id bigint NOT NULL,
    appointment_time timestamp(6) without time zone,
    status integer NOT NULL,
    CONSTRAINT appointment_pkey PRIMARY KEY (id),
    CONSTRAINT fk4apif2ewfyf14077ichee8g06 FOREIGN KEY (patient_id)
        REFERENCES smart_clinic.patient (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkoeb98n82eph1dx43v3y2bcmsl FOREIGN KEY (doctor_id)
        REFERENCES smart_clinic.doctor (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS smart_clinic.appointment
    OWNER to postgres;

-- ------------------------------------------
-- Table: smart_clinic.doctor_available_times
-- ------------------------------------------
CREATE TABLE IF NOT EXISTS smart_clinic.doctor_available_times
(
    doctor_id bigint NOT NULL,
    available_times character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT fkdgs10srq75djpwnb9c22k3lmk FOREIGN KEY (doctor_id)
        REFERENCES smart_clinic.doctor (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS smart_clinic.doctor_available_times
    OWNER to postgres;